openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
tags: 
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
paths:
  /users/signin:
    post:
      tags:
        - User
      summary: signin
      requestBody:
        x-name: body
        required: true
        content:
          application/json: 
            schema:
              required:
              - email
              - password
              - nickname
              properties:
                email:
                  type: string
                  description: 유저 이메일
                  example: swaggerTest@mail.com
                password:
                  type: string
                  description: 유저 비밀 번호
                  example: asidjaiv
                nickname:
                  type: string
                  description: 유저닉네임
                  example: tei
               
          
      responses:
        '200':
          description: 회원가입
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SwaggerTest1a"
                  isSuccess:
                    type: string
                    example: "login1"
                  code:
                    type: string
                    example: "sdkoa"
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: object
                    example: {
                      "email": "swaggerTest@mail.com",
                      "name": "swagger",
                      "preferCategory": [
                        "한식",
                        "일식"
                      ]
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다
  /users/signin/email:
    post:
      tags:
        - User
      summary: email
      requestBody:
        x-name: body
        required: true
        content:
          application/json: 
            schema:
              required:
              - email
              properties:
                nickname:
                  type: string
                  description: 이메일일
                  example: taeyoung132@mail.com
               
          
      responses:
        '200':
          description: 회원가입
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SwaggerTest1a"
                  isSuccess:
                    type: string
                    example: "login1"
                  code:
                    type: string
                    example: "sdkoa"
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: object
                    example: {
                      "email": "swaggerTest@mail.com",
                      "name": "swagger",
                      "preferCategory": [
                        "한식",
                        "일식"
                      ]
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다
                    
  /users/signin/nickcheck:
    post:
      tags:
        - User
      summary: nickcheck
      requestBody:
        x-name: body
        required: true
        content:
          application/json: 
            schema:
              required:
              - nickname
              properties:
                nickname:
                  type: string
                  description: 유저닉네임
                  example: tei
               
          
      responses:
        '200':
          description: 회원가입
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SwaggerTest1a"
                  isSuccess:
                    type: string
                    example: "login1"
                  code:
                    type: string
                    example: "sdkoa"
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: object
                    example: {
                      "email": "swaggerTest@mail.com",
                      "name": "swagger",
                      "preferCategory": [
                        "한식",
                        "일식"
                      ]
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다

  /users/login:
    post:
      tags:
        - User
      summary: login
      requestBody:
        x-name: body
        required: true
        content:
          application/json: 
            schema:
              required:
              - email
              - password
              properties:
                email:
                  type: string
                  description: 이메일
                  example: taeyoung1@mail.com
                password:
                  type: string
                  description: 비밀번호
                  example: abcd1234
               
          
      responses:
        '200':
          description: 회원가입
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "SwaggerTest1a"
                  isSuccess:
                    type: string
                    example: "login1"
                  code:
                    type: string
                    example: "sdkoa"
                  message:
                    type: string
                    example: "success!"
                  data:
                    type: object
                    example: {
                      "email": "swaggerTest@mail.com",
                      "name": "swagger",
                      "preferCategory": [
                        "한식",
                        "일식"
                      ]
                    }
                
        '400':
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON001
                  message:
                    type: string
                    example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 500
                  isSuccess:
                    type: boolean
                    example: false
                  code:
                    type: integer
                    example: COMMON000
                  message:
                    type: string
                    example: 서버 에러, 관리자에게 문의 바랍니다

