/users/signin:
  post:
    tags:
      - User
    summary: 회원가입
    consumes:
      - multipart/form-data  # 문서 타입 지정
    parameters:
      - name: email
        in: formData
        required: true
        type: text
        example: 'email@naver.com'
      - name: password
        in: formData
        required: true
        type: text
        example: 'pw123!'
      - name: nickname
        in: formData
        required: true
        type: text
        example: 'nickname'
    responses:
      '200':
        description: 회원가입
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "SwaggerTest1a"
                isSuccess:
                  type: string
                  example: "login1"
                code:
                  type: string
                  example: "sdkoa"
                message:
                  type: string
                  example: "success!"
                data:
                  type: object
                  example: {
                    "email": "swaggerTest@mail.com",
                    "password": "password",
                    "nickname": "swagger"
                  }
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다
      '500':
        description: 서버 에러
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다

/users/signin/email:
  post:
    tags:
      - User
    summary: 이메일 
    consumes:
      - multipart/form-data  # 문서 타입 지정
    parameters:
      - name: email
        in: formData
        required: true
        type: string
        example: 'email@naver.com'
    responses:
      '200':
        description: 회원가입
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "SwaggerTest1a"
                isSuccess:
                  type: string
                  example: "login1"
                code:
                  type: string
                  example: "sdkoa"
                message:
                  type: string
                  example: "success!"
                data:
                  type: object
                  example: {
                    "email": "swaggerTest@mail.com"
                  }
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다
      '500':
        description: 서버 에러
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다

/users/signin/nickcheck:
  post:
    tags:
      - User
    summary: 닉네임 중복 여부 확인
    consumes:
      - multipart/form-data  # 문서 타입 지정
    parameters:
      - name: nickname
        in: formData
        required: true
        type: string
        example: 'nickname'
    responses:
      '200':
        description: 회원가입
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "SwaggerTest1a"
                isSuccess:
                  type: string
                  example: "login1"
                code:
                  type: string
                  example: "sdkoa"
                message:
                  type: string
                  example: "success!"
                data:
                  type: object
                  example: {
                    "nickname": "swagger"
                  }
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다
      '500':
        description: 서버 에러
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다

/users/login:
  post:
    tags:
      - User
    summary: 로그인
    consumes:
      - multipart/form-data  # 문서 타입 지정
    parameters:
      - name: email
        in: formData
        required: true
        type: string
        example: 'taeyoung1@mail.com'
      - name: password
        in: formData
        required: true
        type: string
        example: 'abcd1234'
    responses:
      '200':
        description: 회원가입
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "SwaggerTest1a"
                isSuccess:
                  type: string
                  example: "login1"
                code:
                  type: string
                  example: "sdkoa"
                message:
                  type: string
                  example: "success!"
                data:
                  type: object
                  example: {
                    "email": "swaggerTest@mail.com",
                    "password": "password"
                  }
      '400':
        description: 잘못된 요청
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 400
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON001
                message:
                  type: string
                  example: 잘못된 요청입니다
      '500':
        description: 서버 에러
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: integer
                  example: 500
                isSuccess:
                  type: boolean
                  example: false
                code:
                  type: integer
                  example: COMMON000
                message:
                  type: string
                  example: 서버 에러, 관리자에게 문의 바랍니다
